#!/bin/bash
# author: Chaubeau <chaubeau.github.io>
# Version: 1.0.0.0
# License: GPL-3.0
# Description:  weath

city_code="101010100"  #beijing,根据需要去www.weather.com.cn 查询相关橙色的code
curl --connect-timeout 3 -s http://www.weather.com.cn/data/cityinfo/${city_code}.html /tmp/we_tmp
cat /tmp/we_tmp|~/bin/jq '.weatherinfo.weather,.weatherinfo.temp1,.weatherinfo.temp2'|sed 's/\"//'|sed 's/\"//'|sed ':a;N;s/\n/ /;ta'|awk '{printf("%s %s-%s\n",$1,$3,$2)}'
