#!/bin/bash
#by chaubeau01@gmail.com

city_code="101010100"  #beijing,根据需要去www.weather.com.cn 查询相关橙色的code
curl -s http://www.weather.com.cn/data/cityinfo/${city_code}.html >.we_tmp


cat ./.we_tmp|./jq '.weatherinfo.weather,.weatherinfo.temp1,.weatherinfo.temp2'|sed 's/\"//'|sed 's/\"//'|sed ':a;N;s/\n/ /;ta'|awk '{printf("%s %s-%s\n",$1,$3,$2)}'
